#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '(.js)$')

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating Javascript:\n"

# Check for eslint
which node_modules/.bin/eslint &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install eslint\033[0m"
  exit 1
fi

for FILE in $STAGED_FILES
do
  node_modules/.bin/eslint --fix "$FILE" > /dev/null
  git add "$FILE"
  node_modules/.bin/eslint "$FILE"


  if [[ "$?" == 0 ]]; then
    echo "\t\033[32mEslint Passed: $FILE\033[0m"
  else
    echo "\t\033[41mEslint Failed: $FILE\033[0m"
    PASS=false
  fi
done

echo "\nJavascript validation completed!\n"

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass Eslint but do not. Please fix the Eslint errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
